"""Added alembic recommended metadata config

Revision ID: 18d6c2593410
Revises: 665b90c8cc71
Create Date: 2024-10-26 08:31:38.279569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d6c2593410'
down_revision = '665b90c8cc71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Campaign', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_Campaign_name'), ['name'])

    with op.batch_alter_table('Dataset', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_Dataset_collection_lpn'), ['collection_lpn'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Dataset', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_Dataset_collection_lpn'), type_='unique')

    with op.batch_alter_table('Campaign', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_Campaign_name'), type_='unique')

    # ### end Alembic commands ###
