"""inital migration

Revision ID: 665b90c8cc71
Revises: 
Create Date: 2024-10-25 20:31:00.702043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665b90c8cc71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('exp_range', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_lpn', sa.String(length=50), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['Campaign.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_lpn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Dataset')
    op.drop_table('Campaign')
    # ### end Alembic commands ###
