"""Added active_campaign bool to Campaign table

Revision ID: b7ac697d1e37
Revises: f9c1dce2a82f
Create Date: 2024-10-26 21:04:55.786489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ac697d1e37'
down_revision = 'f9c1dce2a82f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_campaign', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Campaign', schema=None) as batch_op:
        batch_op.drop_column('active_campaign')

    # ### end Alembic commands ###
