"""added start date to campaigns

Revision ID: f9c1dce2a82f
Revises: 18d6c2593410
Create Date: 2024-10-26 16:03:12.577378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c1dce2a82f'
down_revision = '18d6c2593410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Campaign', schema=None) as batch_op:
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
